CXXFLAGS = -std=c++11 -O3 -pedantic -Wall -march=native -DUSE_QUATERNION_ROTATION #-DDEBUG_CL
CXX = g++
LDFLAGS = -lm -O3 -static

INC_FLAGS = -I. -I../lib/

# For seed MPI:
MPICXX = mpic++
MPICXXFLAGS = -std=c++11 -O3 -pedantic -Wall -march=native -DUSE_QUATERNION_ROTATION
MPILDFLAGS = -lm -O3 -l:libmpi_cxx.so.1.0.2
